name: 📝 Test Report Template
title: "[0.XX.Y] Test Report: 1"
description: "Attn: Release Crew - Create a test report template"
labels: ["Type Release Crew"]

body:
  - type: markdown
    attributes:
      value: |
        ## Test Report Template

        > Note: This is for React Native release crew usage

        Create this issue and fill out the template for your test report

  - type: input
    id: target-minor
    attributes:
      label: Target Minor
      description: Release Minor (for auto-triaging).
      placeholder: "0.74"
    validations:
      required: true

  - type: textarea
    id: system-configuration
    attributes:
      label: Under what system configuration was the test run?
      description: Please provide the host platform + version, as well as the versions of tools such as Xcode. You can easily generate a standardised version of this information by running `npx react-native@<exact-version< info`.
      placeholder: cd your/project/root && npx react-native@<exact-version> info
    validations:
      required: false

  - type: textarea
    id: configurations-covered
    attributes:
      label: Tested configurations
      value: |
        Refer to this [spreadsheet](https://docs.google.com/spreadsheets/d/1p0Zs37ecau7Ty4L_4g1jf7PlivOmIEPjmDYq9Jp8qWI/edit?usp=sharing) for test cases.

        - [ ] RNTester + iOS + Hermes
        - [ ] RNTester + iOS + JSC (only for RN <= 0.78)
        - [ ] RNTester + Android + Hermes
        - [ ] RNTester + Android + JSC (only for RN <= 0.78)
        - [ ] RNTestProject + iOS + Hermes
        - [ ] RNTestProject + iOS + JSC (only for RN <= 0.78)
        - [ ] RNTestProject + Android + Hermes
        - [ ] RNTestProject + Android + JSC (only for RN <= 0.78)

        Close this issue if there are no blocking issues.

        ### Blocking Issues?

        -
